In [5]:
import pandas as pd
import matplotlib.pyplot as pltimpo
import os

In [6]:
path = "./dataset_CO_RH"
files = os.listdir(path)[:-1]

In [7]:
ptf = path + "/" + files[1]
df = pd.read_csv(ptf)
df

,Time (s),CO (ppm),Humidity (%r.h.),Temperature (C),Flow rate (mL/min),Heater voltage (V),R1 (MOhm),R2 (MOhm),R3 (MOhm),R4 (MOhm),...,0.1093,0.1341,0.1151,0.1188,0.1062,0.1290,0.1183,0.1204,0.1087,0.1130
0,0.309,0.0,50.25,26.54,242.0039,0.8928,0.0710,0.1436,0.1059,0.1013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.619,0.0,50.25,26.54,241.5810,0.8960,0.0762,0.1402,0.1080,0.1007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.928,0.0,50.25,26.54,241.1596,0.8980,0.0797,0.1392,0.1112,0.1011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.235,0.0,50.25,26.54,240.7642,0.8983,0.0822,0.1395,0.1142,0.1021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.545,0.0,50.25,26.54,240.7683,0.8990,0.0844,0.1404,0.1172,0.1032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295510,90908.366,0.0,62.28,26.42,0.0000,0.2004,50.0809,58.0787,58.9374,21.7880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295511,90908.671,0.0,62.28,26.42,0.0000,0.2000,46.1185,55.1483,56.9725,23.1202,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295512,90908.976,0.0,62.28,26.42,0.0000,0.2008,41.6775,48.7046,54.8161,22.9051,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295513,90909.281,0.0,62.28,26.42,0.0000,0.2000,38.1549,45.3727,49.5202,22.6808,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295514,90909.585,0.0,62.28,26.42,0.0000,0.2000,35.7839,41.4592,47.3498,21.7880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Cleaning Data
The last 20 columns represent empty data

In [ ]:
df = df.iloc[:,:-20]
df

In [12]:
df.describe()

,Time (s),CO (ppm),Humidity (%r.h.),Temperature (C),Flow rate (mL/min),Heater voltage (V),R1 (MOhm),R2 (MOhm),R3 (MOhm),R4 (MOhm),R5 (MOhm),R6 (MOhm),R7 (MOhm),R8 (MOhm),R9 (MOhm),R10 (MOhm),R11 (MOhm),R12 (MOhm),R13 (MOhm),R14 (MOhm)
count,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000,295515.00000,295515.000000,295515.000000,295515.000000,295515.000000,295515.000000
mean,45451.065113,9.899970,45.748160,26.427411,239.942507,0.355318,15.331624,17.590599,22.473739,19.212285,31.498289,28.963579,31.945923,26.939313,22.39764,25.955875,27.755408,25.772892,22.460504,28.846467
std,26235.249366,6.429014,12.467859,0.103742,1.935526,0.288692,22.708008,26.811309,28.825407,15.841446,26.972746,27.343750,27.697537,19.590679,16.87293,20.847393,20.766412,18.897518,17.276102,22.350802
min,0.309000,0.000000,16.390000,26.140000,0.000000,0.199000,0.032100,0.055900,0.054000,0.039200,0.048200,0.048400,0.052700,0.033000,0.02960,0.036600,0.031100,0.032700,0.033600,0.031600
25%,22738.269500,4.440000,36.140000,26.380000,239.895200,0.200000,0.411300,0.486500,0.592700,2.054600,1.811100,1.583200,1.897900,11.814500,8.60320,7.528300,10.529400,9.665000,7.747100,9.650100
50%,45451.505000,8.890000,46.650000,26.460000,239.972300,0.200000,1.751600,1.390800,4.264200,19.455000,32.815500,23.338100,31.879600,27.066700,21.87230,23.722900,27.281500,25.984400,21.420400,27.141600
75%,68153.354500,15.560000,55.330000,26.500000,240.045600,0.207000,26.172600,29.574900,45.840700,30.686900,51.487500,49.880200,52.707700,40.827700,34.44160,40.641600,42.369400,39.518000,34.488200,45.023900
max,90909.585000,20.000000,72.920000,26.620000,272.606300,0.900900,116.456800,144.618000,175.166600,80.909800,163.032400,168.449100,217.596100,99.194400,81.68830,100.030400,96.936000,129.926100,92.021700,118.874900

## Data Visualization